### ISSUE TITLE
Plans for future development

### ISSUE THREAD

**Issue by vgoklani** [roeierez/infinite-list#8]
Hi,

I just wanted to checkin and see what your plans were for future development. I was thinking about using this library for our iPhone version, and I just wanted to make sure it's still under active development.

Thanks!

**Comment by roeierez** [comment]
Hi,
I am currently working on a big feature to support auto-detect heights, which basically means you don't need to supply the height of each item and it will be detected automatically when rendered.
Since I am working on it on my spare time and I will not compromise on performance, it takes me more time than I thought.
I will be happy to get pull requests or feature requests from you if you have some.
Hope it answer your question.

**Comment by vgoklani** [comment]
Thanks for the response. I'm happy to help in any way possible. If you need assistance testing, etc, please don't hesitate to ask.
